name: opensurge
base: core24
adopt-info: opensurge

grade: stable
confinement: strict

apps:
  opensurge:
    command: snap/command-chain/desktop-launch $SNAP/usr/games/opensurge
    desktop: usr/share/applications/opensurge.desktop
    common-id: org.opensurge2d.OpenSurge
    extensions: [ gnome ]
    environment:
      DISABLE_WAYLAND: '1'
      GTK_USE_PORTAL: '1'
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy # core24
    plugs:
      - home
      - desktop
      - desktop-legacy
      - audio-playback
      - x11
      - opengl
      - joystick

layout:
  /usr/share/games/opensurge:
    bind: $SNAP/usr/share/games/opensurge

parts:
  opensurge:
    after: [ libphysfs, liballegro5, surgescript ]
    source: https://github.com/alemart/opensurge.git
    source-tag: v0.6.1.3
    #source-commit: 
    plugin: cmake
    parse-info: [ usr/share/metainfo/opensurge.appdata.xml ]
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - -DGAME_BUILD_VERSION=snap
      - -DALLEGRO_MONOLITH=OFF
      - -DDESKTOP_INSTALL=ON
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DGAME_DATADIR=/usr/share/games/opensurge
      - -DGAME_BINDIR=/usr/games
      - -DDESKTOP_ENTRY_PATH=/usr/share/applications
      - -DDESKTOP_ICON_PATH=/usr/share/pixmaps
      - -DDESKTOP_METAINFO_PATH=/usr/share/metainfo
      - -DPHYSFS_INCLUDE_PATH=$CRAFT_STAGE/usr/include
      - -DPHYSFS_LIBRARY_PATH=$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
      - -DALLEGRO_INCLUDE_PATH=$CRAFT_STAGE/usr/include
      - -DALLEGRO_LIBRARY_PATH=$CRAFT_STAGE/usr/lib/
      - -DSURGESCRIPT_INCLUDE_PATH=$CRAFT_STAGE/usr/include
      - -DSURGESCRIPT_LIBRARY_PATH=$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
    build-packages:
      - build-essential
    stage-packages:
      - libasyncns0
      - libatk1.0-0
      - libcairo2
      - libdatrie1
      - libflac12
      - libfontconfig1
      - libfreetype6
      - libgdk-pixbuf2.0-0
      - libglvnd0
      - libglx0
      - libgraphite2-3
      - libgtk-3-0
      - libharfbuzz0b
      - libjpeg-turbo8
      - libogg0
      - libopengl0
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libpng16-16
      - libpulse0
      - libsndfile1
      - libthai0
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - libx11-6
      - libxau6
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libproxy1v5 # core24

  surgescript:
    source: https://github.com/alemart/surgescript.git
    source-tag: v0.6.1
    #source-commit: 
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DWANT_EXECUTABLE=OFF
      - -DWANT_STATIC=OFF
    build-packages:
      - build-essential

  libphysfs:
    source: https://github.com/icculus/physfs/archive/refs/tags/release-3.2.0.tar.gz
    source-checksum: sha256/1991500eaeb8d5325e3a8361847ff3bf8e03ec89252b7915e1f25b3f8ab5d560
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DPHYSFS_BUILD_TEST=OFF
      - -DPHYSFS_BUILD_DOCS=OFF
      - -DPHYSFS_BUILD_STATIC=OFF
    build-packages:
      - build-essential

  liballegro5:
    after: [ libphysfs ]
    source: https://github.com/liballeg/allegro5/releases/download/5.2.11.2/allegro-5.2.11.2.tar.gz
    source-checksum: sha256/f035fe128dd5f2412c32add41ed4058ad8154f6e9571084574487d67dbdbaae0
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DWANT_DEMO=OFF
      - -DWANT_DOCS=OFF
      - -DWANT_EXAMPLES=OFF
      - -DWANT_TESTS=OFF
      - -DWANT_MP3=OFF
      - -DWANT_DUMB=OFF
      - -DWANT_FLAC=OFF
      - -DWANT_VIDEO=OFF
      - -DPHYSFS_INCLUDE_DIR=$CRAFT_STAGE/usr/include
      - -DPHYSFS_LIBRARY=$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libphysfs.so
    build-packages: # lean A5
      - build-essential
      - zlib1g-dev
      - libvorbis-dev
      - libogg-dev
      - libpulse-dev
      - libpng-dev
      - libjpeg8-dev
      - libfreetype6-dev
      - libgtk-3-dev
      - libglu1-mesa-dev
      - libgl1-mesa-dev
    stage-packages:
      - libasyncns0
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatspi2.0-0
      - libcairo-gobject2
      - libcairo2
      - libdatrie1
      - libepoxy0
      - libflac12
      - libfontconfig1
      - libfreetype6
      - libfribidi0
      - libgdk-pixbuf2.0-0
      - libglvnd0
      - libglx0
      - libgraphite2-3
      - libgtk-3-0
      - libharfbuzz0b
      - libjpeg-turbo8
      - libogg0
      - libopengl0
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpixman-1-0
      - libpng16-16
      - libpulse0
      - libsndfile1
      - libthai0
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libx11-6
      - libxau6
      - libxcb-render0
      - libxcb-shm0
      - libxcb1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxrandr2
      - libxrender1
